cluster:
  mkdir -p {params.D} &&
  rm -f {params.D}/{params.clog_prefix}.slurm-out && 
  sbatch
    -J {params.jobname}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    {resources.gpu}
    --output={params.D}/{params.clog_prefix}.slurm-out
    --parsable
default-resources:
  - mem_mb=1000
  - time="00:05:00"
max-jobs-per-second: 10
max-status-checks-per-second: 1
cluster-status: status-sacct.sh
local-cores: 1
latency-wait: 60
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: False
use-envmodules: True
