# Input Settings: initialize base input folder names,
# dataset collections, and algorithms to run over
input_settings:

    # Directory for singularity images, absolute path
    sif_dir: "$(pwd)/images_singularity/"
    overlay_dir: "$(pwd)/images_singularity_overlay"
    gpu_flag: "--nv"

    # Base input directory
    input_dir : "inputs"

    # Subdirectory of inputs that datasets are placed in
    dataset_dir: "SERGIO_DS5"
    full_dataset_dir: "SERGIO_DS5"

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   exprData: scRNA-Seq expression data file. Cells are along the
    #            columns and genes are along the rows.
    #   cellData: a file containing pseudotime ordering, or any other 
    #             information about cells.
    #   trueEdges: Name of the refrence network file in the
    #              edge list format. Needed for evaluation.
    datasets:

        - name: "net0"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net1"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net2"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net3"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net4"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net5"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net6"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net7"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net8"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net9"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net10"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net11"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net12"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net13"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net14"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net0_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net1_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net2_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net3_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net4_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net5_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net6_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net7_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net8_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net9_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net10_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net11_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net12_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net13_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

        - name: "net14_sh6.5_perc80"
          exprData: "ExpressionData.csv"  
          cellData: "SlingshotPT.csv"
          trueEdges: "refNetwork.csv"

    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #


    algorithms:

        - name: "CICT"
          params: 
              should_run: [False]
              groundTruth: ['refNetwork.csv']
              edgeTypes: ['ewMImm,ewMIempirical, Pearson,Euclidean,Granger']  #  ewMImm,ewMIempirical, efMIshrink,ewMIshrink , efMImm,efMIempirical, Pearson,Kendall,Spearman, Euclidean,Granger,L10NormManhattan,
              supervised.positiveClass: ['c,rc']  # c:causal edges, 'c,rc': causal and reversecausal
              supervised.negativeClass: ['r']  # r:random edges, 'rc': reversecausal
              supervised.gtProp: [.2] #proportion of GT used for classification
              supervised.train: [.3] #proportion of classification records used for training
              fp.fn.cost: [1/5]  #False positive to False Negative cost ratio for threshold identification


        - name: "CNNC"
          params: 
              should_run: [True]
              useGPU: [True]


        - name: "DEEPDRIM"
          params: 
              should_run: [True]
              useGPU: [True]


        - name: "DEEPDRIM4"
          params: 
              should_run: [True]
              useGPU: [True]


        - name: "DEEPDRIM5"
          params: 
              should_run: [True]
              useGPU: [True]


        - name: "DEEPDRIM6"
          params: 
              should_run: [True]
              useGPU: [True]


        - name: "DEEPDRIM7"
          params: 
              should_run: [True]
              useGPU: [True]
              numBatches: [10]


        - name: "PIDC"
          params: 
              should_run: [True]


        - name: "GRNVBEM"
          params: 
              should_run: [True]


        - name: "GENIE3"
          params: 
              should_run: [True]  #<===


        - name: "GRNBOOST2"
          params: 
              should_run: [True] #<===
              
              
        - name: "PPCOR"
          params: 
              should_run: [True]  #<====
              #should_run: [False]
              # p-value cutoff
              # Used in parsing output
              pVal: [0.01]


        - name: "RANDOM"
          params: 
              should_run: [True] #<===


        - name: "SCODE"
          params:
              should_run: [True]  #<==== Error
                  #should_run: [False]
              z: [10]
              nIter: [1000]
              nRep: [6]


        - name: "SCNS"
          params: 
              should_run: [True] #<=== error
              
              
        - name: "SINCERITIES"
          params: 
              should_run: [True]  #<====Error
              nBins: [10]


        - name: "LEAP"
          params: 
              should_run: [True]
              #should_run: [False]
              # Default maxLag value is 0.33
              maxLag: [0.33]


        - name: "GRISLI"
          params: 
              should_run: [True]
              L: [10]
              R: [3000]
              alphaMin: [0.0]


        - name: "SINGE"
          params: 
              should_run: [True]
              lambda: [0.01]
              dT: [15]
              num_lags: [5]
              kernel_width: [0.5]
              prob_zero_removal: [0]
              prob_remove_samples: [0.0]
              family: ["gaussian"]
              num_replicates: [6]


        - name: "SCRIBE"
          params: 
              should_run: [True]
              ### required parameters
              # a list of delay values
              delay: ["5"]
              # any of 'RDI', 'uRDI', 'cRDI', or 'ucRDI'
              method: ['ucRDI']
              # lower detection limit (expression below this 
              # will be treated as zero.
              lowerDetectionLimit: [0]
              # expressionFamily: for synthetic data use uninormal
              #  for mRNA count data use negbinomial.size()
              expressionFamily: ['uninormal']
              ### optional but recommended parameters
              # log transform expression values or not
              log: [False]
              # ignore pseudotime values (and use experimental
              # time points instead), recommended True for synthetic data
              # False for real mRNA data
              ignorePT: [True]


# Output Settings: initialize base output folder names
output_settings:

    # Base output directory
    output_dir: "outputs"
    output_prefix: "SERGIO_DS5"
