# Input Settings: initialize base input folder names,
# dataset collections, and algorithms to run over
input_settings:

    # Base input directory
    input_dir : "inputs"

    # Subdirectory of inputs that datasets are placed in
    dataset_dir: "simulated"

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   ex_filename: scRNA-Seqexpression file name
    #
    #   pt_filename: a file containing pseudotime ordering
    #
    datasets:
        - name: "HSC"
          ex_filename: "ExpressionData.csv"
          pt_filename: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"




    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    algorithms:
        - name: "SCODE"
          params:
              should_run: [False]
              nGenes: [11]
              z: [4]
              nCells: [570]         
              nIter: [100]
              nRep: [5]

        #- name: "SCNS"
        #  params: 
        #      should_run: [False]
              
              
        - name: "SINCERITIES"
          params: 
              should_run: [False]
                            
              
        - name: "PIDC"
          params: 
              should_run: [False]


        - name: "GRNVBEM"
          params: 
              should_run: [False]

              

        - name: "GENIE3"
          params: 
              should_run: [True]
              
              
              
        - name: "GRNBOOST2"
          params: 
              should_run: [False]
              
              
              
        - name: "LEAP"
          params: 
              should_run: [False]
              
              
                            
        #- name: "JUMP3"
        #  params: 
        #      should_run: [False]
              
              
              
        - name: "PPCOR"
          params: 
              should_run: [False]
              pVal: [0.01]
              
              
              
        - name: "GRISLI"
          params: 
              should_run: [False]
              L: [10]
              R: [1000]
              alphaMin: [0.3]


        - name: "SCINGE"
          params: 
              should_run: [False]



# Output Settings: initialize base output folder names
output_settings:

    # Base output directory
    output_dir: "outputs"
